# -*- coding: utf-8 -*-
image: ubuntu

env:
  - LC_ALL="en_US.utf-8"
  - LC_ALL="en_US.ascii"

stages:
  - build

PythonBuild:
  stage: build
  script:
        - apt-get update -qq && apt-get install -y -qq python3 python3-pip git
        - python3 -m pip install -r requirements.txt
        - python3 WikiTags.py