image: ubuntu

stages:
  - build

PythonBuild:
  stage: build
  script: 
        - apt-get update && apt-get install python3
        - python3 -m pip install -r requirements.txt
        - python3 WikiTags.py