# -*- coding: utf-8 -*-
image: ubuntu

stages:
  - build

PythonBuild:
  stage: build
  script:
        - apt-get update -qq && apt-get install -y -qq python3 python3-pip git
        - python3 -m pip install -r requirements.txt
        - export PYTHONIOENCODING=utf8
        - python3 WikiTags.py